In [101]:
import pandas as pd
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from imblearn.combine import SMOTEENN

In [102]:
df=pd.read_csv("machine failure.csv")
df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

In [103]:
x=df.drop('Machine failure',axis=1)
x

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,M24855,M,298.8,308.4,1604,29.5,14,0,0,0,0,0
9996,9997,H39410,H,298.9,308.4,1632,31.8,17,0,0,0,0,0
9997,9998,M24857,M,299.0,308.6,1645,33.4,22,0,0,0,0,0
9998,9999,H39412,H,299.0,308.7,1408,48.5,25,0,0,0,0,0
9999,10000,M24859,M,299.0,308.7,1500,40.2,30,0,0,0,0,0

In [104]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

# Identify columns with object data type
object_cols = x.select_dtypes(include='object').columns

# Convert object columns to float
for col in object_cols:
    x[col] = x[col].str.extract('(\d+)').astype(float)

# Scale numeric columns using MinMaxScaler
minmax = MinMaxScaler()
train_minmax = minmax.fit_transform(x)

# Create a new DataFrame with scaled values
x = pd.DataFrame(train_minmax, columns=x.columns)

c:\Users\PRATHAMESH RAUT\anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:473: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
c:\Users\PRATHAMESH RAUT\anaconda3\lib\site-packages\sklearn\preprocessing\_data.py:474: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)

In [105]:
y=df['Machine failure']
y

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    0
Name: Machine failure, Length: 10000, dtype: int64

In [106]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1,test_size=0.2)

In [107]:
from sklearn.ensemble import RandomForestClassifier

In [108]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [109]:
from sklearn.impute import SimpleImputer

# Create an imputer object with the desired strategy
imputer = SimpleImputer(strategy='mean')

# Impute missing values in x_train
x_train_imputed = imputer.fit_transform(x_train)

# Fit the RandomForestClassifier on the imputed data
model_rf.fit(x_train_imputed, y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [110]:
# Impute missing values in x_test using the same imputer object
x_test_imputed = imputer.transform(x_test)

# Make predictions on the imputed test data
y_pred = model_rf.predict(x_test_imputed)

In [111]:
model_rf.score(x_test_imputed,y_test)

0.9995

In [112]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1937
           1       1.00      0.98      0.99        63

    accuracy                           1.00      2000
   macro avg       1.00      0.99      1.00      2000
weighted avg       1.00      1.00      1.00      2000

In [113]:
accscore=accuracy_score(y_test,y_pred)
print(accscore)

0.9995